server:
  port: 1000
  servlet:
    context-path: /${spring.application.name}

spring:
  messages:
    basename: i18n/messages
  application:
    name: springboot-mybatisplus
  # mysql
  datasource:
    username: root
    password: 1qaz!QAZ
    url: jdbc:mysql://localhost:3306/2022?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000

      stat-view-servlet.allow: true

# mybatis plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath*:com/example/mapper/xml/*Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0




